Add additional API methods
FosterCommerce/klaviyoconnect pull request #94
Opened 2022-11-16 11:49 UTC by delux589

## Notes

- [Add additional API methods to help us get additional klaviyo details about a profile.](https://3.basecamp.com/3091851/buckets/9025087/todos/5319230042#__recording_5532941676)

2022-11-16 17:19 UTC, fantasticmachine commented on src/services/Api.php
> +    public function getProfileFromList($listId, $email)
Need to include Typing on this method. Indicate what type of thing the params are, and the type of thing that is being returned.

2022-11-16 17:19 UTC, fantasticmachine commented on src/services/Api.php
> +    public function getProfile($profileId)
Need to include Typing on this method. Indicate what type of thing the params are, and the type of thing that is being returned.

2022-11-16 17:19 UTC, fantasticmachine commented on src/variables/Variable.php
> +    public function profileFromList($listId, $email)
Need to include Typing on this method. Indicate what type of thing the params are, and the type of thing that is being returned.

2022-11-16 17:19 UTC, fantasticmachine commented on src/variables/Variable.php
> +    public function profile($profileId)
Need to include Typing on this method. Indicate what type of thing the params are, and the type of thing that is being returned.

2022-11-16 17:24 UTC, fantasticmachine requested changes
We need to include the PHP Type Declarations for the new methods. See See https://www.php.net/manual/en/language.types.declarations.php

This is also going to be tricky since we have  Craft 3 and Craft 4 versions of the plugin in 2 different develop branches. I think master is the Craft 3 version so concentrate on that. 

Your changes should probably be merged into the develop-craft3 branch.
I'm not sure you'll be able to merge into develop-craft4 but the changes should also be added there too.

Sorry, it's a bit of a pain because we need 2 versions of the plugin.

2022-11-17 16:34 UTC, delux589 commented
Closing this as I created this branch off the master branch where I should have created it off develop-craft3 branch. Here is the more relevant PR.

2022-11-17 16:34 UTC, closed without merging